---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}  
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
  annotations:
    metallb.universe.tf/address-pool: pool
spec:
  selector:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: 9292
  # type: LoadBalancer
  # ports:
  # - port: 80
  #   protocol: TCP
  #   targetPort: 9292
