---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "comment.fullname" . }}
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
  annotations:
    metallb.universe.tf/address-pool: pool
spec:
  selector:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
  # ports:
  # - name: http
  #   port: {{ .Values.service.externalPort }}
  #   protocol: TCP
  #   targetPort: {{ .Values.service.internalPort }}  
  ports:  
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
