apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: redit
    component: post-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: post-deployment
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: post-deployment
    spec:
      containers:
      - image: storik/post:1.0
        name: post
        env:
        - name: POST_DATABASE_HOST
          value: post-db
