---
apiVersion: v1
kind: Service
metadata:
  name: ui  
  labels:
    app: reddit
    component: ui
spec:  
  selector:
    app: reddit
    component: ui    
  ports:
  - name: http 
    port: 80
    protocol: TCP
    targetPort: 9292   
  # type: LoadBalancer  
  # ports:
  # - port: 80
  #   protocol: TCP
  #   targetPort: 9292  
  
  
